name: Release
run-name: Release v${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main

permissions:
  contents: write
  checks: write    # Required for publishing test results
  pull-requests: write  # Required for PR comments

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v4

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4

      - name: Set up permissions
        run: |
          chmod +x bin/log_json bin/version.sh
          chmod +x test/run_tests.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq

      - name: Inject version into shell script
        run: sed -i "s/VERSION_PLACEHOLDER/${{ steps.gitversion.outputs.semVer }}/" bin/version.sh

      - name: Run tests
        run: |
          cd test
          ./run_tests.sh
          ls -la ../test-results.xml  # Verify file exists
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  # Run this step even if tests failed
        with:
          files: "test-results.xml"
          report_individual_runs: true
          check_name: "Test Results"
      
      - name: Create release package
        run: |
          mkdir -p release
          tar -czf release/bash-utils.tar.gz -C bin/ .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          name: Release v${{ steps.gitversion.outputs.semVer }}
          draft: false
          prerelease: false
          files: |
            release/bash-utils.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
