name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v1

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Display version
        run: echo "Version: ${{ steps.gitversion.outputs.semVer }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          name: Release ${{ steps.gitversion.outputs.semVer }}
          files: bin/log_json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
