name: Release
run-name: Release v${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v4

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4

      - name: Set up permissions
        run: |
          chmod +x bin/log_json bin/version.sh
          chmod +x test/*.sh

      - name: Inject version into shell script
        run: sed -i "s/VERSION_PLACEHOLDER/${{ steps.gitversion.outputs.semVer }}/" bin/version.sh

      - name: Run tests
        run: ./test/run_tests.sh

      - name: Create release package
        run: |
          mkdir -p release
          tar -czf release/bash-utils-${{ steps.gitversion.outputs.semVer }}.tar.gz bin/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          name: Release v${{ steps.gitversion.outputs.semVer }}
          draft: false
          prerelease: false
          files: |
            release/bash-utils-${{ steps.gitversion.outputs.semVer }}.tar.gz
            bin/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
