name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('**/test.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-
      
      - name: Set up permissions
        run: |
          chmod +x bin/log_json bin/version.sh
          chmod +x test/run_tests.sh

      - name: Install dependencies
        run: |
          # Check what's already available
          echo "Checking pre-installed tools..."
          jq --version 2>/dev/null && echo "jq: ✓ available" || echo "jq: ✗ missing"
          bats --version 2>/dev/null && echo "bats: ✓ available" || echo "bats: ✗ missing"
          
          # Install only what's needed
          if ! command -v jq &> /dev/null || ! command -v bats &> /dev/null; then
            echo "Installing missing dependencies..."
            # Update apt cache only if packages need to be installed
            if [ ! -f /var/cache/apt/pkgcache.bin ] || [ $(find /var/cache/apt/pkgcache.bin -mtime +1) ]; then
              sudo apt-get update
            fi
            sudo apt-get install -y bats jq
          else
            echo "All dependencies already available, skipping installation"
          fi

      - name: Run tests
        run: ./test/run_tests.sh
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && !github.event.pull_request.draft
        with:
          files: "test-results.xml"
          report_individual_runs: true
          check_name: "Test Results"
          comment_mode: always
