name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  REQUIRED_PACKAGES: "jq bats"

jobs:
  test:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up file permissions
        run: |
          find bin/ -type f -exec chmod +x {} \;
          find test/ -name "*.sh" -exec chmod +x {} \;

      - name: Install system dependencies
        run: |
          echo "Installing system dependencies: $REQUIRED_PACKAGES"
          sudo apt-get update -qq
          sudo apt-get install -y $REQUIRED_PACKAGES

      - name: Run tests
        run: ./test/run_tests.sh
      
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && !github.event.pull_request.draft
        with:
          files: "test-results.xml"
          report_individual_runs: true
          check_name: "Test Results"
          comment_mode: always
          action_fail: false
          action_fail_on_inconclusive: false
