name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up permissions
        run: |
          chmod +x bin/log_json bin/version.sh
          chmod +x test/run_tests.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats jq

      - name: Run tests
        run: ./test/run_tests.sh
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "test-results.xml"
          report_individual_runs: true
          check_name: "Test Results"
          comment_mode: create new
